modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"
issueTrackerURL="https://github.com/Ninhoplayer6gg/ascension-of-Genesis/issues"

[[mods]]
modId="projectgenesis"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''Original-superhero powers mod powered by the Palladium framework.'''

[[dependencies.projectgenesis]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.projectgenesis]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.projectgenesis]]
modId="palladium"
mandatory=true
versionRange="[4.5,)"
ordering="AFTER"
side="BOTH"
